### PR TITLE
Aligned all kernel patches to get the BPI-M2U to the updated 3.10.105 release.

### PR DESCRIPTION
**Pull request by dan-and**
Hi,

Since my patches work pretty well on my side, it would be great if you update your base to the current 3.10.105 linux kernel release.

### CODE REVIEW

**Comment by ThomasKaiser** [comment]
@BPI-SINOVOIP you ignore @dan-and's work now since half a year and this pull request now since 5 weeks. Why exactly?

Is it really that important that your customers run a kernel release outdated since 2.5 years containing loads of security issues?

**Comment by Fredy72** [comment]
Hi, I confirm the error in the update on 3.10.105. Version 3.10.104 was compiled well.
In file included from include/linux/crypto.h:21:0,
from include/crypto/algapi.h:15,
from include/crypto/internal/skcipher.h:16,
from crypto/blkcipher.c:17:
crypto/blkcipher.c: In function ‘blkcipher_walk_next’:
crypto/blkcipher.c:241:18: error: ‘struct blkcipher_walk’ has no member named ‘blocksize’
bsize = min(walk->blocksize, n);
^
include/linux/kernel.h:674:9: note: in definition of macro ‘min’
typeof(x) _min1 = (x); \
^
crypto/blkcipher.c:241:18: error: ‘struct blkcipher_walk’ has no member named ‘blocksize’
bsize = min(walk->blocksize, n);
^
include/linux/kernel.h:674:21: note: in definition of macro ‘min’
typeof(x) _min1 = (x); \
^
include/linux/kernel.h:676:17: warning: comparison of distinct pointer types lacks a cast
(void) (&_min1 == &_min2); \
^
crypto/blkcipher.c:241:10: note: in expansion of macro ‘min’
bsize = min(walk->blocksize, n);
^
crypto/blkcipher.c: In function ‘blkcipher_copy_iv’:
crypto/blkcipher.c:285:20: error: ‘struct blkcipher_walk’ has no member named ‘blocksize’
unsigned bs = walk->blocksize;
^
crypto/blkcipher.c: In function ‘blkcipher_walk_virt’:
crypto/blkcipher.c:310:6: error: ‘struct blkcipher_walk’ has no member named ‘blocksize’
walk->blocksize = crypto_blkcipher_blocksize(desc->tfm);
^
crypto/blkcipher.c: In function ‘blkcipher_walk_phys’:
crypto/blkcipher.c:319:6: error: ‘struct blkcipher_walk’ has no member named ‘blocksize’
walk->blocksize = crypto_blkcipher_blocksize(desc->tfm);
^
crypto/blkcipher.c: In function ‘blkcipher_walk_virt_block’:
crypto/blkcipher.c:357:6: error: ‘struct blkcipher_walk’ has no member named ‘blocksize’
walk->blocksize = blocksize;
^

**Comment by dan-and** [comment]
Hi Fredy72,

Why didn't you created a issue at my branch ? 
I fixed it in the meanwhile when I updated to 3.10.106 

Dan
